version: '2'
services:
 db:
  container_name: mongodb
  image:  library/mongo
  ports:
   - "27017:27017"
 web:
  container_name: springboot
  image: java
  environment: 
   - MONGODB_URI = mongodb
  ports:
   - "8080:8080"
  depends_on:
   - db
